### ISSUE TITLE
Enforce Singleton Status of Support Objects

### ISSUE THREAD

**Issue by Cogswatch** [OPEnSLab-OSU/Loom-Network#1]
A great majority of the classes that support the behavior of the network are described as _"This class is meant to be generated once"_ which is synonymous with Singleton. Consider adding some initialization controls to prevent this from being violated, especially if it will cause system failure. 

A great resource on these patters/idioms can be found [here](https://medium.com/@sinethneranjana/5-ways-to-write-a-singleton-and-why-you-shouldnt-1cf078562376). Considering the overhead, and the time of initialization needed, I'd recommend an early loading approach, especially since it adds minimal overhead and will be similar to approaches used in loom core.

**Comment by prototypicalpro** [comment]
Could you list which objects you're referring to?

**Comment by prototypicalpro** [comment]
After discussion, this was deemed unnecessary, as all Loom-Network objects can be created multiple times and still function.
